name: ci
on:  
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: ci_jobs
      run: make ci_jobs TARGET_VERSION="${GITHUB_REF:10}" TARGET_BUILD="${{ github.run_number }}" TARGET_REGISTRY_TOKEN="${{ secrets.TARGET_REGISTRY_TOKEN }}" TARGET_REGISTRY_USER="${{ github.actor }}" GITHUB_ENV="${GITHUB_ENV}"

